#!/bin/bash

DAEMON="wcluster/bin/Release/App.exe -p $SERVER_PORT --cache-dir __cache"

echo "Starting the server"
$DAEMON > $SERVER_LOG &

PID=$(jobs -l | grep "\$DAEMON" | awk '{ print $2 }')
echo "Server PID is: $PID"

trap serverEnd EXIT

TOTAL_WAITS=10
WAIT_INT=3
SERVER_OK=false

l=$(( TOTAL_WAITS + 1 ))
for (( i=1; i<$l; i++ ))
do
    echo "Waiting for server: ($i/$TOTAL_WAITS)"

    { grep -q "Listening on:" $SERVER_LOG 2>&1; } > /dev/null

    if [ $? == "0" ]; then
        echo "  Service is ready"
        SERVER_OK=true
        break
    fi

    isServerOk
    if [ $? != "0" ]; then
        break;
    fi

    sleep $WAIT_INT
done
